
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: MicroserviceTest1234
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083

